a=input('enter your temperature');
b=input('enter your temperature');
c=input('enter your temperature');
d=input('enter your temperature');
e=linspace(-0.5,0.5,100);
f1=1./(1+exp(e./((0.026*a)/300)));
f2=1./(1+exp(e./((0.026*b)/300)));
f3=1./(1+exp(e./((0.026*c)/300)));
f4=1./(1+exp(e./((0.026*d)/300)));
subplot(2,2,1);
plot(e,f1);
ylabel('probability');
xlabel('energy');
title('The Fermi-Dirac Distribution Curve');
subplot(2,2,2);
plot(e,f2);
ylabel('probability');
xlabel('energy');
title('The Fermi-Dirac Distribution Curve');
subplot(2,2,3);
plot(e,f3);
ylabel('probability');
xlabel('energy');
title('The Fermi-Dirac Distribution Curve');
subplot(2,2,4);
plot(e,f4);
ylabel('probability');
xlabel('energy');
title('The Fermi-Dirac Distribution Curve');
